### PR TITLE
Heruoxin/Delegated-scopes-manager_readme.mdb

### PR DESCRIPTION
**Pull request by fahrulmustari6**
Love that

### CODE REVIEW

**Comment by fahrulmustari6** [comment]
http://www.github.com/

**Comment by fahrulmustari6** [comment]
Collaborator

**Comment by fahrulmustari6** [comment]
Contribution.mdb

**Comment by fahrulmustari6** [comment]
``dir"

**Review by friendinme98 — APPROVED** [review]

**Pull request closed without merging**
